---
http_interactions:
- request:
    method: post
    uri: https://conda-parser.libraries.io/parse
    body:
      encoding: UTF-8
      string: file=name%3A%20testingenv%0Achannels%3A%0A%20%20-%20defaults%0Adependencies%3A%0A%20%20-%20pip%0A%20%20-%20sqlite%3D3.29.0%3Dh7b6447c_0%0A%20%20-%20pip%3A%0A%20%20%20%20-%20urllib3&filename=environment.yml
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Contenttype:
      - multipart/form-data
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - gunicorn/19.9.0
      Date:
      - Tue, 27 Aug 2019 17:55:06 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '887'
      Via:
      - 1.1 google
      Alt-Svc:
      - clear
    body:
      encoding: UTF-8
      string: '{"channels":["defaults"],"lockfile":[{"name":"_libgcc_mutex","requirement":"0.1"},{"name":"ca-certificates","requirement":"2019.5.15"},{"name":"certifi","requirement":"2019.6.16"},{"name":"libedit","requirement":"3.1.20181209"},{"name":"libffi","requirement":"3.2.1"},{"name":"libgcc-ng","requirement":"9.1.0"},{"name":"libstdcxx-ng","requirement":"9.1.0"},{"name":"ncurses","requirement":"6.1"},{"name":"openssl","requirement":"1.1.1c"},{"name":"pip","requirement":"19.2.2"},{"name":"python","requirement":"3.7.4"},{"name":"readline","requirement":"7.0"},{"name":"setuptools","requirement":"41.0.1"},{"name":"sqlite","requirement":"3.29.0"},{"name":"tk","requirement":"8.6.8"},{"name":"wheel","requirement":"0.33.4"},{"name":"xz","requirement":"5.2.4"},{"name":"zlib","requirement":"1.2.11"}],"manifest":[{"name":"pip","requirement":"19.2.2"},{"name":"sqlite","requirement":"3.29.0"}]}

        '
    http_version:
  recorded_at: Tue, 27 Aug 2019 17:55:06 GMT
recorded_with: VCR 5.0.0
