---
http_interactions:
- request:
    method: post
    uri: https://conda-parser.libraries.io/parse
    body:
      encoding: UTF-8
      string: file=name%3A%20testingenv%0Achannels%3A%0A%20%20-%20defaults%0Adependencies%3A%0A%20%20-%20beautifulsoup4%3D4.7.1%3Dpy37_1%0A%20%20-%20biopython%3D1.74%3Dpy37h7b6447c_0%0A%20%20-%20certifi%3D2019.6.16%3Dpy37_1%0A%20%20-%20ncurses%3D6.1%3Dhe6710b0_1%0A%20%20-%20numpy%3D1.16.4%3Dpy37h7e9f1db_0%0A%20%20-%20openssl%3D1.1.1c%3Dh7b6447c_1%0A%20%20-%20pip%0A%20%20-%20python%3D3.7.3%3Dh0371630_0%0A%20%20-%20readline%3D7.0%3Dh7b6447c_5%0A%20%20-%20setuptools%0A%20%20-%20sqlite%3D3.29.0%3Dh7b6447c_0&filename=environment.yml
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Contenttype:
      - multipart/form-data
      Expect:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - gunicorn/19.9.0
      Date:
      - Thu, 22 Aug 2019 15:00:05 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '1824'
      Via:
      - 1.1 google
      Alt-Svc:
      - clear
    body:
      encoding: UTF-8
      string: '{"channels":["defaults"],"lockfile":[{"name":"_libgcc_mutex","requirement":"0.1"},{"name":"beautifulsoup4","requirement":"4.7.1"},{"name":"biopython","requirement":"1.74"},{"name":"blas","requirement":"1.0"},{"name":"ca-certificates","requirement":"2019.5.15"},{"name":"certifi","requirement":"2019.6.16"},{"name":"intel-openmp","requirement":"2019.4"},{"name":"libedit","requirement":"3.1.20181209"},{"name":"libffi","requirement":"3.2.1"},{"name":"libgcc-ng","requirement":"9.1.0"},{"name":"libgfortran-ng","requirement":"7.3.0"},{"name":"libstdcxx-ng","requirement":"9.1.0"},{"name":"mkl","requirement":"2019.4"},{"name":"mkl-service","requirement":"2.0.2"},{"name":"mkl_fft","requirement":"1.0.14"},{"name":"mkl_random","requirement":"1.0.2"},{"name":"ncurses","requirement":"6.1"},{"name":"numpy","requirement":"1.16.4"},{"name":"numpy-base","requirement":"1.16.4"},{"name":"openssl","requirement":"1.1.1c"},{"name":"pip","requirement":"19.2.2"},{"name":"python","requirement":"3.7.3"},{"name":"readline","requirement":"7.0"},{"name":"setuptools","requirement":"41.0.1"},{"name":"six","requirement":"1.12.0"},{"name":"soupsieve","requirement":"1.9.2"},{"name":"sqlite","requirement":"3.29.0"},{"name":"tk","requirement":"8.6.8"},{"name":"wheel","requirement":"0.33.4"},{"name":"xz","requirement":"5.2.4"},{"name":"zlib","requirement":"1.2.11"}],"manifest":[{"name":"beautifulsoup4","requirement":"4.7.1"},{"name":"biopython","requirement":"1.74"},{"name":"certifi","requirement":"2019.6.16"},{"name":"ncurses","requirement":"6.1"},{"name":"numpy","requirement":"1.16.4"},{"name":"openssl","requirement":"1.1.1c"},{"name":"pip","requirement":"19.2.2"},{"name":"python","requirement":"3.7.3"},{"name":"readline","requirement":"7.0"},{"name":"setuptools","requirement":"41.0.1"},{"name":"sqlite","requirement":"3.29.0"}]}

        '
    http_version:
  recorded_at: Thu, 22 Aug 2019 15:00:05 GMT
recorded_with: VCR 5.0.0
